server:
  port: 5555

spring:
  application:
    name: api-gateway

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-A
    api-b:
      path: /api-b/**
      serviceId: service-B
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:2222/
    api-b-url:
      path: /api-b-url/**
      url: http://localhost:3333/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
